/* eslint-disable */
export default function partRetorno(toyoId, partId) {
    var partInfo = [
        {
            id: 1,
            torsoId: 1,
            part: 1,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ta',
            desc: '',
        },
        {
            id: 2,
            torsoId: 1,
            part: 3,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ta',
            desc: '',
        },
        {
            id: 3,
            torsoId: 1,
            part: 4,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ta',
            desc: '',
        },
        {
            id: 4,
            torsoId: 1,
            part: 5,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ta',
            desc: '',
        },
        {
            id: 5,
            torsoId: 1,
            part: 6,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ta',
            desc: '',
        },
        {
            id: 6,
            torsoId: 1,
            part: 7,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'tsu',
            desc: '',
        },
        {
            id: 7,
            torsoId: 1,
            part: 8,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'tsu',
            desc: '',
        },
        {
            id: 8,
            torsoId: 1,
            part: 9,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'tsu',
            desc: '',
        },
        {
            id: 9,
            torsoId: 1,
            part: 10,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'tsu',
            desc: '',
        },
        {
            id: 10,
            torsoId: 2,
            part: 1,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'nyi',
            desc: '',
        },
        {
            id: 11,
            torsoId: 2,
            part: 3,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'nyi',
            desc: '',
        },
        {
            id: 12,
            torsoId: 2,
            part: 4,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'nyi',
            desc: '',
        },
        {
            id: 13,
            torsoId: 2,
            part: 5,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'nyi',
            desc: '',
        },
        {
            id: 14,
            torsoId: 2,
            part: 6,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'nyi',
            desc: '',
        },
        {
            id: 15,
            torsoId: 2,
            part: 7,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ma',
            desc: '',
        },
        {
            id: 16,
            torsoId: 2,
            part: 8,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ma',
            desc: '',
        },
        {
            id: 17,
            torsoId: 2,
            part: 9,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ma',
            desc: '',
        },
        {
            id: 18,
            torsoId: 2,
            part: 10,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ma',
            desc: '',
        },
        {
            id: 19,
            torsoId: 3,
            part: 1,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ming',
            desc: '',
        },
        {
            id: 20,
            torsoId: 3,
            part: 3,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ming',
            desc: '',
        },
        {
            id: 21,
            torsoId: 3,
            part: 4,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ming',
            desc: '',
        },
        {
            id: 22,
            torsoId: 3,
            part: 5,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ming',
            desc: '',
        },
        {
            id: 23,
            torsoId: 3,
            part: 6,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ming',
            desc: '',
        },
        {
            id: 24,
            torsoId: 3,
            part: 7,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'yue',
            desc: '',
        },
        {
            id: 25,
            torsoId: 3,
            part: 8,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'yue',
            desc: '',
        },
        {
            id: 26,
            torsoId: 3,
            part: 9,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'yue',
            desc: '',
        },
        {
            id: 27,
            torsoId: 3,
            part: 10,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'yue',
            desc: '',
        },
        {
            id: 28,
            torsoId: 4,
            part: 1,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'da',
            desc: '',
        },
        {
            id: 29,
            torsoId: 4,
            part: 3,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'da',
            desc: '',
        },
        {
            id: 30,
            torsoId: 4,
            part: 4,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'da',
            desc: '',
        },
        {
            id: 31,
            torsoId: 4,
            part: 5,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'da',
            desc: '',
        },
        {
            id: 32,
            torsoId: 4,
            part: 6,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'da',
            desc: '',
        },
        {
            id: 33,
            torsoId: 4,
            part: 7,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'tu',
            desc: '',
        },
        {
            id: 34,
            torsoId: 4,
            part: 8,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'tu',
            desc: '',
        },
        {
            id: 35,
            torsoId: 4,
            part: 9,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'tu',
            desc: '',
        },
        {
            id: 36,
            torsoId: 4,
            part: 10,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'tu',
            desc: '',
        },
        {
            id: 37,
            torsoId: 5,
            part: 1,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'wang',
            desc: '',
        },
        {
            id: 38,
            torsoId: 5,
            part: 3,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'wang',
            desc: '',
        },
        {
            id: 39,
            torsoId: 5,
            part: 4,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'wang',
            desc: '',
        },
        {
            id: 40,
            torsoId: 5,
            part: 5,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'wang',
            desc: '',
        },
        {
            id: 41,
            torsoId: 5,
            part: 6,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'wang',
            desc: '',
        },
        {
            id: 42,
            torsoId: 5,
            part: 7,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'hu',
            desc: '',
        },
        {
            id: 43,
            torsoId: 5,
            part: 8,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'hu',
            desc: '',
        },
        {
            id: 44,
            torsoId: 5,
            part: 9,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'hu',
            desc: '',
        },
        {
            id: 45,
            torsoId: 5,
            part: 10,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'hu',
            desc: '',
        },
        {
            id: 46,
            torsoId: 6,
            part: 1,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'mi',
            desc: '',
        },
        {
            id: 47,
            torsoId: 6,
            part: 3,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'mi',
            desc: '',
        },
        {
            id: 48,
            torsoId: 6,
            part: 4,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'mi',
            desc: '',
        },
        {
            id: 49,
            torsoId: 6,
            part: 5,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'zu',
            desc: '',
        },
        {
            id: 50,
            torsoId: 6,
            part: 6,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'zu',
            desc: '',
        },
        {
            id: 51,
            torsoId: 6,
            part: 7,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'chi',
            desc: '',
        },
        {
            id: 52,
            torsoId: 6,
            part: 8,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'chi',
            desc: '',
        },
        {
            id: 53,
            torsoId: 6,
            part: 9,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'chi',
            desc: '',
        },
        {
            id: 54,
            torsoId: 6,
            part: 10,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'chi',
            desc: '',
        },
        {
            id: 55,
            torsoId: 7,
            part: 1,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ha',
            desc: '',
        },
        {
            id: 56,
            torsoId: 7,
            part: 3,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ha',
            desc: '',
        },
        {
            id: 57,
            torsoId: 7,
            part: 4,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ha',
            desc: '',
        },
        {
            id: 58,
            torsoId: 7,
            part: 5,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ru',
            desc: '',
        },
        {
            id: 59,
            torsoId: 7,
            part: 6,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ru',
            desc: '',
        },
        {
            id: 60,
            torsoId: 7,
            part: 7,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ru',
            desc: '',
        },
        {
            id: 61,
            torsoId: 7,
            part: 8,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ko',
            desc: '',
        },
        {
            id: 62,
            torsoId: 7,
            part: 9,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ko',
            desc: '',
        },
        {
            id: 63,
            torsoId: 7,
            part: 10,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ko',
            desc: '',
        },
        {
            id: 64,
            torsoId: 17,
            part: 1,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: '',
            desc: '',
        },
        {
            id: 65,
            torsoId: 18,
            part: 1,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: '',
            desc: '',
        },
        {
            id: 66,
            torsoId: 19,
            part: 1,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: '',
            desc: '',
        },
        {
            id: 67,
            torsoId: 8,
            part: 1,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ra',
            desc: ''
        },
        {
            id: 68,
            torsoId: 8,
            part: 3,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ra',
            desc: ''
        },
        {
            id: 69,
            torsoId: 8,
            part: 4,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ra',
            desc: ''
        },
        {
            id: 70,
            torsoId: 8,
            part: 5,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ra',
            desc: ''
        },
        {
            id: 71,
            torsoId: 8,
            part: 6,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ra',
            desc: ''
        },
        {
            id: 72,
            torsoId: 8,
            part: 7,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ra',
            desc: ''
        },
        {
            id: 73,
            torsoId: 8,
            part: 8,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ra',
            desc: ''
        },
        {
            id: 74,
            torsoId: 8,
            part: 9,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ra',
            desc: ''
        },
        {
            id: 75,
            torsoId: 8,
            part: 10,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ra',
            desc: ''
        },
        {
            id: 76,
            torsoId: 9,
            part: 1,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'pu',
            desc: ''
        },
        {
            id: 77,
            torsoId: 9,
            part: 3,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'pu',
            desc: ''
        },
        {
            id: 78,
            torsoId: 9,
            part: 4,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'pu',
            desc: ''
        },
        {
            id: 79,
            torsoId: 9,
            part: 5,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'pu',
            desc: ''
        },
        {
            id: 80,
            torsoId: 9,
            part: 6,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'pu',
            desc: ''
        },
        {
            id: 81,
            torsoId: 9,
            part: 7,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'pu',
            desc: ''
        },
        {
            id: 82,
            torsoId: 9,
            part: 8,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'pu',
            desc: ''
        },
        {
            id: 83,
            torsoId: 9,
            part: 9,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'pu',
            desc: ''
        },
        {
            id: 84,
            torsoId: 9,
            part: 10,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'pu',
            desc: ''
        },
        {
            id: 85,
            torsoId: 10,
            part: 1,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'pa',
            desc: ''
        },
        {
            id: 86,
            torsoId: 10,
            part: 3,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'pa',
            desc: ''
        },
        {
            id: 87,
            torsoId: 10,
            part: 4,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'pa',
            desc: ''
        },
        {
            id: 88,
            torsoId: 10,
            part: 5,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'pa',
            desc: ''
        },
        {
            id: 89,
            torsoId: 10,
            part: 6,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'pa',
            desc: ''
        },
        {
            id: 90,
            torsoId: 10,
            part: 7,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'pa',
            desc: ''
        },
        {
            id: 91,
            torsoId: 10,
            part: 8,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'pa',
            desc: ''
        },
        {
            id: 92,
            torsoId: 10,
            part: 9,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'pa',
            desc: ''
        },
        {
            id: 93,
            torsoId: 10,
            part: 10,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'pa',
            desc: ''
        },
        {
            id: 94,
            torsoId: 11,
            part: 1,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'el',
            desc: ''
        },
        {
            id: 95,
            torsoId: 11,
            part: 3,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'el',
            desc: ''
        },
        {
            id: 96,
            torsoId: 11,
            part: 4,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'el',
            desc: ''
        },
        {
            id: 97,
            torsoId: 11,
            part: 5,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'el',
            desc: ''
        },
        {
            id: 98,
            torsoId: 11,
            part: 6,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'el',
            desc: ''
        },
        {
            id: 99,
            torsoId: 11,
            part: 7,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'el',
            desc: ''
        },
        {
            id: 100,
            torsoId: 11,
            part: 8,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'el',
            desc: ''
        },
        {
            id: 101,
            torsoId: 11,
            part: 9,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'el',
            desc: ''
        },
        {
            id: 102,
            torsoId: 11,
            part: 10,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'el',
            desc: ''
        },
        {
            id: 103,
            torsoId: 12,
            part: 1,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ha',
            desc: ''
        },
        {
            id: 104,
            torsoId: 12,
            part: 3,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ha',
            desc: ''
        },
        {
            id: 105,
            torsoId: 12,
            part: 4,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ha',
            desc: ''
        },
        {
            id: 106,
            torsoId: 12,
            part: 5,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ha',
            desc: ''
        },
        {
            id: 107,
            torsoId: 12,
            part: 6,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ha',
            desc: ''
        },
        {
            id: 108,
            torsoId: 12,
            part: 7,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ha',
            desc: ''
        },
        {
            id: 109,
            torsoId: 12,
            part: 8,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ha',
            desc: ''
        },
        {
            id: 110,
            torsoId: 12,
            part: 9,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ha',
            desc: ''
        },
        {
            id: 111,
            torsoId: 12,
            part: 10,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ha',
            desc: ''
        },
        {
            id: 112,
            torsoId: 13,
            part: 1,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'sp',
            desc: ''
        },
        {
            id: 113,
            torsoId: 13,
            part: 3,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'sp',
            desc: ''
        },
        {
            id: 114,
            torsoId: 13,
            part: 4,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'sp',
            desc: ''
        },
        {
            id: 115,
            torsoId: 13,
            part: 5,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'sp',
            desc: ''
        },
        {
            id: 116,
            torsoId: 13,
            part: 6,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'sp',
            desc: ''
        },
        {
            id: 117,
            torsoId: 13,
            part: 7,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'sp',
            desc: ''
        },
        {
            id: 118,
            torsoId: 13,
            part: 8,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'sp',
            desc: ''
        },
        {
            id: 119,
            torsoId: 13,
            part: 9,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'sp',
            desc: ''
        },
        {
            id: 120,
            torsoId: 13,
            part: 10,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'sp',
            desc: ''
        },
        {
            id: 121,
            torsoId: 14,
            part: 1,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'on',
            desc: ''
        },
        {
            id: 122,
            torsoId: 14,
            part: 3,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'on',
            desc: ''
        },
        {
            id: 123,
            torsoId: 14,
            part: 4,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'on',
            desc: ''
        },
        {
            id: 124,
            torsoId: 14,
            part: 5,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'on',
            desc: ''
        },
        {
            id: 125,
            torsoId: 14,
            part: 6,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'on',
            desc: ''
        },
        {
            id: 126,
            torsoId: 14,
            part: 7,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'on',
            desc: ''
        },
        {
            id: 127,
            torsoId: 14,
            part: 8,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'on',
            desc: ''
        },
        {
            id: 128,
            torsoId: 14,
            part: 9,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'on',
            desc: ''
        },
        {
            id: 129,
            torsoId: 14,
            part: 10,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'on',
            desc: ''
        },
        {
            id: 130,
            torsoId: 15,
            part: 1,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'pe',
            desc: ''
        },
        {
            id: 131,
            torsoId: 15,
            part: 3,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'pe',
            desc: ''
        },
        {
            id: 132,
            torsoId: 15,
            part: 4,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'pe',
            desc: ''
        },
        {
            id: 133,
            torsoId: 15,
            part: 5,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'pe',
            desc: ''
        },
        {
            id: 134,
            torsoId: 15,
            part: 6,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'pe',
            desc: ''
        },
        {
            id: 135,
            torsoId: 15,
            part: 7,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'pe',
            desc: ''
        },
        {
            id: 136,
            torsoId: 15,
            part: 8,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'pe',
            desc: ''
        },
        {
            id: 137,
            torsoId: 15,
            part: 9,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'pe',
            desc: ''
        },
        {
            id: 138,
            torsoId: 15,
            part: 10,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'pe',
            desc: ''
        },
        {
            id: 139,
            torsoId: 16,
            part: 1,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'do',
            desc: ''
        },
        {
            id: 140,
            torsoId: 16,
            part: 3,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'do',
            desc: ''
        },
        {
            id: 141,
            torsoId: 16,
            part: 4,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'do',
            desc: ''
        },
        {
            id: 142,
            torsoId: 16,
            part: 5,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'do',
            desc: ''
        },
        {
            id: 143,
            torsoId: 16,
            part: 6,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'do',
            desc: ''
        },
        {
            id: 144,
            torsoId: 16,
            part: 7,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'do',
            desc: ''
        },
        {
            id: 145,
            torsoId: 16,
            part: 8,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'do',
            desc: ''
        },
        {
            id: 146,
            torsoId: 16,
            part: 9,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'do',
            desc: ''
        },
        {
            id: 147,
            torsoId: 16,
            part: 10,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'do',
            desc: ''
        },
        {
            id: 148,
            torsoId: 23,
            part: 1,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'lq',
            desc: ''
        },
        {
            id: 149,
            torsoId: 23,
            part: 3,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'lq',
            desc: ''
        },
        {
            id: 150,
            torsoId: 23,
            part: 4,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'lq',
            desc: ''
        },
        {
            id: 151,
            torsoId: 23,
            part: 5,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'lq',
            desc: ''
        },
        {
            id: 152,
            torsoId: 23,
            part: 6,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'lq',
            desc: ''
        },
        {
            id: 153,
            torsoId: 23,
            part: 7,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'lq',
            desc: ''
        },
        {
            id: 154,
            torsoId: 23,
            part: 8,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'lq',
            desc: ''
        },
        {
            id: 155,
            torsoId: 23,
            part: 9,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'lq',
            desc: ''
        },
        {
            id: 156,
            torsoId: 23,
            part: 10,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'lq',
            desc: ''
        }
    ]

    return partInfo.filter(info => {
        return info.torsoId == toyoId && info.part == partId 
    })
}
