export default function partRetorno(toyoId, partId) {
    var partInfo = [
        {
            id: 1,
            torsoId: 1,
            part: 1,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ta',
            desc: '',
        },
        {
            id: 2,
            torsoId: 1,
            part: 3,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ta',
            desc: '',
        },
        {
            id: 3,
            torsoId: 1,
            part: 4,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ta',
            desc: '',
        },
        {
            id: 4,
            torsoId: 1,
            part: 5,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ta',
            desc: '',
        },
        {
            id: 5,
            torsoId: 1,
            part: 6,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ta',
            desc: '',
        },
        {
            id: 6,
            torsoId: 1,
            part: 7,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'tsu',
            desc: '',
        },
        {
            id: 7,
            torsoId: 1,
            part: 8,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'tsu',
            desc: '',
        },
        {
            id: 8,
            torsoId: 1,
            part: 9,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'tsu',
            desc: '',
        },
        {
            id: 9,
            torsoId: 1,
            part: 10,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'tsu',
            desc: '',
        },
        {
            id: 10,
            torsoId: 2,
            part: 1,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'nyi',
            desc: '',
        },
        {
            id: 11,
            torsoId: 2,
            part: 3,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'nyi',
            desc: '',
        },
        {
            id: 12,
            torsoId: 2,
            part: 4,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'nyi',
            desc: '',
        },
        {
            id: 13,
            torsoId: 2,
            part: 5,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'nyi',
            desc: '',
        },
        {
            id: 14,
            torsoId: 2,
            part: 6,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'nyi',
            desc: '',
        },
        {
            id: 15,
            torsoId: 2,
            part: 7,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ma',
            desc: '',
        },
        {
            id: 16,
            torsoId: 2,
            part: 8,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ma',
            desc: '',
        },
        {
            id: 17,
            torsoId: 2,
            part: 9,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ma',
            desc: '',
        },
        {
            id: 18,
            torsoId: 2,
            part: 10,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ma',
            desc: '',
        },
        {
            id: 19,
            torsoId: 3,
            part: 1,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ming',
            desc: '',
        },
        {
            id: 20,
            torsoId: 3,
            part: 3,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ming',
            desc: '',
        },
        {
            id: 21,
            torsoId: 3,
            part: 4,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ming',
            desc: '',
        },
        {
            id: 22,
            torsoId: 3,
            part: 5,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ming',
            desc: '',
        },
        {
            id: 23,
            torsoId: 3,
            part: 6,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ming',
            desc: '',
        },
        {
            id: 24,
            torsoId: 3,
            part: 7,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'yue',
            desc: '',
        },
        {
            id: 25,
            torsoId: 3,
            part: 8,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'yue',
            desc: '',
        },
        {
            id: 26,
            torsoId: 3,
            part: 9,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'yue',
            desc: '',
        },
        {
            id: 27,
            torsoId: 3,
            part: 10,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'yue',
            desc: '',
        },
        {
            id: 28,
            torsoId: 4,
            part: 1,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'da',
            desc: '',
        },
        {
            id: 29,
            torsoId: 4,
            part: 3,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'da',
            desc: '',
        },
        {
            id: 30,
            torsoId: 4,
            part: 4,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'da',
            desc: '',
        },
        {
            id: 31,
            torsoId: 4,
            part: 5,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'da',
            desc: '',
        },
        {
            id: 32,
            torsoId: 4,
            part: 6,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'da',
            desc: '',
        },
        {
            id: 33,
            torsoId: 4,
            part: 7,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'tu',
            desc: '',
        },
        {
            id: 34,
            torsoId: 4,
            part: 8,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'tu',
            desc: '',
        },
        {
            id: 35,
            torsoId: 4,
            part: 9,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'tu',
            desc: '',
        },
        {
            id: 36,
            torsoId: 4,
            part: 10,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'tu',
            desc: '',
        },
        {
            id: 37,
            torsoId: 5,
            part: 1,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'wang',
            desc: '',
        },
        {
            id: 38,
            torsoId: 5,
            part: 3,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'wang',
            desc: '',
        },
        {
            id: 39,
            torsoId: 5,
            part: 4,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'wang',
            desc: '',
        },
        {
            id: 40,
            torsoId: 5,
            part: 5,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'wang',
            desc: '',
        },
        {
            id: 41,
            torsoId: 5,
            part: 6,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'wang',
            desc: '',
        },
        {
            id: 42,
            torsoId: 5,
            part: 7,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'hu',
            desc: '',
        },
        {
            id: 43,
            torsoId: 5,
            part: 8,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'hu',
            desc: '',
        },
        {
            id: 44,
            torsoId: 5,
            part: 9,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'hu',
            desc: '',
        },
        {
            id: 45,
            torsoId: 5,
            part: 10,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'hu',
            desc: '',
        },
        {
            id: 46,
            torsoId: 6,
            part: 1,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'mi',
            desc: '',
        },
        {
            id: 47,
            torsoId: 6,
            part: 3,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'mi',
            desc: '',
        },
        {
            id: 48,
            torsoId: 6,
            part: 4,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'mi',
            desc: '',
        },
        {
            id: 49,
            torsoId: 6,
            part: 5,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'zu',
            desc: '',
        },
        {
            id: 50,
            torsoId: 6,
            part: 6,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'zu',
            desc: '',
        },
        {
            id: 51,
            torsoId: 6,
            part: 7,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'chi',
            desc: '',
        },
        {
            id: 52,
            torsoId: 6,
            part: 8,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'chi',
            desc: '',
        },
        {
            id: 53,
            torsoId: 6,
            part: 9,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'chi',
            desc: '',
        },
        {
            id: 54,
            torsoId: 6,
            part: 10,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'chi',
            desc: '',
        },
        {
            id: 55,
            torsoId: 7,
            part: 1,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ha',
            desc: '',
        },
        {
            id: 56,
            torsoId: 7,
            part: 3,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ha',
            desc: '',
        },
        {
            id: 57,
            torsoId: 7,
            part: 4,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ha',
            desc: '',
        },
        {
            id: 58,
            torsoId: 7,
            part: 5,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ru',
            desc: '',
        },
        {
            id: 59,
            torsoId: 7,
            part: 6,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ru',
            desc: '',
        },
        {
            id: 60,
            torsoId: 7,
            part: 7,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ru',
            desc: '',
        },
        {
            id: 61,
            torsoId: 7,
            part: 8,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ko',
            desc: '',
        },
        {
            id: 62,
            torsoId: 7,
            part: 9,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ko',
            desc: '',
        },
        {
            id: 63,
            torsoId: 7,
            part: 10,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: 'ko',
            desc: '',
        },
        {
            id: 64,
            torsoId: 17,
            part: 1,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: '',
            desc: '',
        },
        {
            id: 65,
            torsoId: 18,
            part: 1,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: '',
            desc: '',
        },
        {
            id: 66,
            torsoId: 19,
            part: 1,
            retroBone: 0,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            prefix: '',
            desc: '',
        }
    ]

    return partInfo.filter(info => {
        return info.torsoId == toyoId && info.part == partId 
    })
}
