/* eslint-disable */
export default function toyoRetorno(id) {
    var toyo = [
        {
            id: 1,
            existe: 1,
            material: 0,
            bodyType: 2,
            rarity: 1,
            size: 110,
            variants: 1,
            colors: 1,
            cyber: 0,
            name: "Tatsu",
            desc: " "
        },
        {
            id: 2,
            existe: 1,
            material: 0,
            bodyType: 1,
            rarity: 2,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            name: "Nyima",
            desc: " "
        },
        {
            id: 3,
            existe: 1,
            material: 0,
            bodyType: 1,
            rarity: 3,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            name: "Ming Yue",
            desc: " "
        },
        {
            id: 4,
            existe: 1,
            material: 0,
            bodyType: 2,
            rarity: 3,
            size: 105,
            variants: 1,
            colors: 1,
            cyber: 0,
            name: "Datu",
            desc: " "
        },
        {
            id: 5,
            existe: 1,
            material: 0,
            bodyType: 2,
            rarity: 4,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            name: "Wang Hu",
            desc: " "
        },
        {
            id: 6,
            existe: 1,
            material: 0,
            bodyType: 2,
            rarity: 5,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            name: "Mizuchi",
            desc: " "
        },
        {
            id: 7,
            existe: 1,
            material: 0,
            bodyType: 2,
            rarity: 6,
            size: 105,
            variants: 1,
            colors: 1,
            cyber: 0,
            name: "Haruko",
            desc: " "
        },
        {
            id: 8,
            existe: 1,
            material: 0,
            bodyType: 2,
            rarity: 1,
            size: 90,
            variants: 1,
            colors: 2,
            cyber: 0,
            name: "Rato",
            desc: " "
        },
        {
            id: 9,
            existe: 1,
            material: 0,
            bodyType: 3,
            rarity: 2,
            size: 100,
            variants: 1,
            colors: 2,
            cyber: 0,
            name: "Pug",
            desc: " "
        },
        {
            id: 10,
            existe: 1,
            material: 0,
            bodyType: 3,
            rarity: 3,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            name: "Panda",
            desc: " "
        },
        {
            id: 11,
            existe: 1,
            material: 0,
            bodyType: 3,
            rarity: 3,
            size: 125,
            variants: 1,
            colors: 1,
            cyber: 0,
            name: "Eleph",
            desc: " "
        },
        {
            id: 12,
            existe: 1,
            material: 0,
            bodyType: 3,
            rarity: 3,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            name: "Hawk",
            desc: " "
        },
        {
            id: 13,
            existe: 1,
            material: 0,
            bodyType: 2,
            rarity: 4,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            name: "Sphynx",
            desc: " "
        },
        {
            id: 14,
            existe: 1,
            material: 0,
            bodyType: 1,
            rarity: 4,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            name: "Onca",
            desc: " "
        },
        {
            id: 15,
            existe: 1,
            material: 0,
            bodyType: 1,
            rarity: 5,
            size: 90,
            variants: 1,
            colors: 1,
            cyber: 0,
            name: "Perereca",
            desc: " "
        },
        {
            id: 16,
            existe: 1,
            material: 0,
            bodyType: 3,
            rarity: 6,
            size: 90,
            variants: 1,
            colors: 1,
            cyber: 0,
            name: "Doge",
            desc: " "
        },
        {
            id: 17,
            existe: 0,
            material: 1,
            bodyType: 2,
            rarity: 3,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            name: "Pumpkin",
            desc: " "
        },
        {
            id: 18,
            existe: 0,
            material: 2,
            bodyType: 2,
            rarity: 3,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            name: "Skull",
            desc: " "
        },
        {
            id: 19,
            existe: 0,
            material: 3,
            bodyType: 2,
            rarity: 3,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            name: "Clawn",
            desc: " "
        }
    ]

    return toyo.filter(info => {
        return info.id == id
    })
}
