/* eslint-disable */
export default function toyoRetorno(id) {
    var toyo = [
        {
            id: 1,
            existe: 1,
            material: 0,
            bodyType: 2,
            rarity: 1,
            size: 110,
            variants: 1,
            colors: 1,
            cyber: 0,
            name: "Tatsu",
            desc: " "
        },
        {
            id: 2,
            existe: 1,
            material: 0,
            bodyType: 1,
            rarity: 2,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            name: "Nyima",
            desc: " "
        },
        {
            id: 3,
            existe: 1,
            material: 0,
            bodyType: 1,
            rarity: 3,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            name: "Ming Yue",
            desc: " "
        },
        {
            id: 4,
            existe: 1,
            material: 0,
            bodyType: 2,
            rarity: 3,
            size: 105,
            variants: 1,
            colors: 1,
            cyber: 0,
            name: "Datu",
            desc: " "
        },
        {
            id: 5,
            existe: 1,
            material: 0,
            bodyType: 2,
            rarity: 4,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            name: "Wang Hu",
            desc: " "
        },
        {
            id: 6,
            existe: 1,
            material: 0,
            bodyType: 2,
            rarity: 5,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            name: "Mizuchi",
            desc: " "
        },
        {
            id: 7,
            existe: 1,
            material: 0,
            bodyType: 2,
            rarity: 6,
            size: 105,
            variants: 1,
            colors: 1,
            cyber: 0,
            name: "Haruko",
            desc: " "
        },
        {
            id: 8,
            existe: 1,
            material: 0,
            bodyType: 2,
            rarity: 1,
            size: 90,
            variants: 1,
            colors: 2,
            cyber: 0,
            name: "Slicky",
            desc: " "
        },
        {
            id: 9,
            existe: 1,
            material: 0,
            bodyType: 3,
            rarity: 2,
            size: 100,
            variants: 1,
            colors: 2,
            cyber: 0,
            name: "Don Barko",
            desc: " "
        },
        {
            id: 10,
            existe: 1,
            material: 0,
            bodyType: 3,
            rarity: 3,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            name: "BlkEy3z",
            desc: " "
        },
        {
            id: 11,
            existe: 1,
            material: 0,
            bodyType: 3,
            rarity: 3,
            size: 95,
            variants: 1,
            colors: 1,
            cyber: 0,
            name: "Gaja",
            desc: " "
        },
        {
            id: 12,
            existe: 1,
            material: 0,
            bodyType: 3,
            rarity: 3,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            name: "Rocker",
            desc: " "
        },
        {
            id: 13,
            existe: 1,
            material: 0,
            bodyType: 2,
            rarity: 4,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            name: "Uzi",
            desc: " "
        },
        {
            id: 14,
            existe: 1,
            material: 0,
            bodyType: 1,
            rarity: 4,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            name: "Yawara",
            desc: " "
        },
        {
            id: 15,
            existe: 1,
            material: 0,
            bodyType: 1,
            rarity: 5,
            size: 90,
            variants: 1,
            colors: 1,
            cyber: 0,
            name: "Ribbit",
            desc: " "
        },
        {
            id: 16,
            existe: 1,
            material: 0,
            bodyType: 3,
            rarity: 6,
            size: 90,
            variants: 1,
            colors: 1,
            cyber: 0,
            name: "Doge",
            desc: " "
        },
        {
            id: 17,
            existe: 0,
            material: 1,
            bodyType: 2,
            rarity: 3,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            name: "Pumpkin",
            desc: " "
        },
        {
            id: 18,
            existe: 0,
            material: 2,
            bodyType: 2,
            rarity: 3,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            name: "Skull",
            desc: " "
        },
        {
            id: 19,
            existe: 0,
            material: 3,
            bodyType: 2,
            rarity: 3,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            name: "Clown",
            desc: " "
        },
        {
            id: 20,
            existe: 0,
            material: 1,
            bodyType: 2,
            rarity: 3,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            name: "Santa Claus",
            desc: " "
        },
        {
            id: 21,
            existe: 0,
            material: 2,
            bodyType: 2,
            rarity: 3,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            name: "KIlljoy",
            desc: " "
        },
        {
            id: 22,
            existe: 0,
            material: 3,
            bodyType: 2,
            rarity: 3,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            name: "Rudolph",
            desc: " "
        },
        {
            id: 23,
            existe: 1,
            material: 0,
            bodyType: 3,
            rarity: 5,
            size: 100,
            variants: 1,
            colors: 1,
            cyber: 0,
            name: "Lao Qing",
            desc: " "
        },
    ]

    return toyo.filter(info => {
        return info.id == id
    })
}
